### ISSUE TITLE
Help to build on old fedora computer

### ISSUE THREAD

**Issue by alejokalderon** [jackburton79/ocs-agent#33]
Hi Mr.

Do you know how can I do to make it works on old fedora computers? When i make sh setup.sh it say's THINSTATION_PATH: no such file or directory
SET_ENV: no such file or directory

The computers aren't thinstation but are old fedora computers of a NGO.

Can you help me?

Regards!

**Comment by jackburton79** [comment]
Hi,
You don't need to execute setup.sh. That is only for building within Thinstation.
To build, just issue "make".
Since there is no "make install", you need to copy the executable manually, in whatever directory you like (usually /usr/local/bin), and put a cron job which launches it every now and then.
